# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7beae0bef3c45e7c3a5f27eaa97297e2b684e54b75a57dad71d4106046845d8c753ea9e7dbd2e40899b9fea5dba6ced996237cb900e89f27140134793232580e

test:
  secret_key_base: 79f7bac9405481609b3ea2b98eda93e122c99f9b0418ec8c2c117e8de8e6c86a59de7cae06832b40bea7b841111e1c19bd49af8e06eaf9e1812719e0dc6f33f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
